version: "3.8"
services:
  sniper-bot:
    build: .
    container_name: solana-sniper-bot
    env_file:
      - .env
    volumes:
      - ./wallets:/app/wallets
      - ./config.json:/app/config.json
    restart: unless-stopped
    command: ["./cli", "start"]
    logging:
      options:
        max-size: 10m
